### PR TITLE
fix mismatched exported/upscaled usage

### PR DESCRIPTION
**Pull request by gidoBOSSftw5731**
It seems to want to grab frames from the wrong directory, this fixes that.

### CODE REVIEW

**Comment by k4yt3x** [comment]
First of all, if you're trying to say `self.extracted_frames`, then it won't make sense.
If you replace it like this, then you're putting the original frames back into a video instead of the processed and upscaled frames.

Second of all, the variable `self.exported_frames` doesn't exist. I'll have to assume that you've never tested your PR.

There are no errors in the original code, so this PR won't me merged.
However, thank you for submitting the PR.

**Comment by gidoBOSSftw5731** [comment]
I did test this, and in fact, I couldnt use this in its original state, error below

```
[image2 @ 0x563a236b1980] Could find no file with path '/tmp/video2x/tmp1txsmrz0/extracted_%d.png' and index in the range 0-4
/tmp/video2x/tmp1txsmrz0/extracted_%d.png: No such file or directory
```

full log: https://hastebin.com/ajakalugip.bash

**Comment by k4yt3x** [comment]
There's no such variable as `self.exported_frames` in the original `src/upscale.py`.

Also, your upscale failed not due to a v2x error but the fact that waifu2x-converter was not properly set up.
image

You got the error because the frames were never processed, not a variable error.

If you still claim that your mod "fixed" the program, then double check the output file's resolution against the original input video.

**Comment by gidoBOSSftw5731** [comment]
Ah, you're right, I didnt notice that the resolution didnt change, even though the file size did

**Pull request closed without merging**
