### PR TITLE
Add support for Real-ESRGAN, plus various fixes (hangs, async video, etc.)

### PR DESCRIPTION
**Pull request by arximboldi**
This picks up the work in  #1102 by @aa-ko to introduce Real-ESRGAN support, adding support for all models exposed by `realesrgan-ncnn-py` and testing it outside of a Docker container.

Additionally, I have fixed a few issues that I've found. I wasn't sure whether you prefer to have multiple smaller PR, or to just review all at once. The work is separated into multiple commits so I can still split into multiple PR's if you prefer.

These are the **highlights** from this PR:
- A fix for the mysterious hangs described in #780, plus other smaller issues with the application hanging during the teardown sequence
- A fix for the out of sync videos described in #1132 . This is actually related to the previous issue, as it was all related to fundamental problems with how
- A fix for the terminal output flooding issues with some upscalers: https://github.com/k4yt3x/video2x/issues/1079#issuecomment-2189674030

There are also some **smaller changes** that I'm not sure you agree with, but that I think are quite convenient:
- A `shell.nix` environment that allows installing all the system dependencies in an isolated environment, by simply running `nix-shell`. This was crucial for me to be able to run and test the program locally outside of a Docker container
- Minor improvements to the logging system (proper acknowledgement of the `-l` flag, and introduction of a new `-L` flag).

---

Thank you @aa-ko for starting the work on integrating Real-ESRGAN. It's model `realesr-animevideov3` is giving me incredible results, with image quality comparable or better for anime than `realcugan`, yet much faster!

Thank you @k4yt3x for this incredible tool. Looking into the code has shown me how much love there is into it and it is working super well for me now!

### CODE REVIEW

**Comment by twardoch** [comment]
@arximboldi 

```
class KillableListener(Listener, KillableThreadMixin):
    """
    A killable version of pyinput.keyboard.Listener, as joining()
    seems to hang on some systems even after properly calling close().
    """
    pass
```

in https://github.com/arximboldi/video2x/blob/realesrgan/video2x/video2x.py#L131C1-L136C9 causes a fail where pynput is not available. Because Python tries to subclass from Listener. You should define that class in a scoped way.

**Comment by twardoch** [comment]
@arximboldi Also when I try running with realesrgan on Google Colab, I get

```
Unrecognized option 'fps_mode'. Error splitting the argument list: Option not found
```

(which seems to be referenced in https://github.com/arximboldi/video2x/blob/realesrgan/video2x/decoder.py )

**Comment by twardoch** [comment]
Turns out that 'fps_mode' is a relatively new option in ffmpeg, and the standard Google Colab environment installs an older ffmpeg. But I was able to work around it with: 

```
!apt-get update
!apt-get install -y --no-install-recommends \
    python3-pip libvulkan-dev glslang-dev glslang-tools \
    build-essential swig ninja-build nvidia-driver-535 \
    mpv xserver-xorg-video-dummy xvfb libomp5
!sudo curl -L https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz -o /usr/local/bin/ffmpeg.tar.xz
%cd /usr/local/bin/
!7z e /usr/local/bin/ffmpeg.tar.xz
!7z e /usr/local/bin/ffmpeg.tar
!sudo chmod a+rx /usr/local/bin/ffmpeg
```

**Comment by twardoch** [comment]
Similarly, to work around the poor integration of `Listener`, I was able to work around it in Google Colab by providing: 

```
%env DISPLAY=:0
class Listener:
    pass

from video2x import Video2X
video2x = Video2X()
```

But that’s not how it should work :)

**Comment by k4yt3x** [comment]
Thank you all @arximboldi @aa-ko @twardoch for the amazing work here. I've been very busy with work and several other non-FOSS projects over the last half of this year. Sorry that I missed this PR came in. I've been just getting way too many messages from GitHub and I didn't notice this PR was submitted. I only saw if after I completed the 6.0.0 rewrite.

It has always been my goal to introduce RealESRGAN in Video2X. I managed to do it in the rewrite. Take a look if you're still interested.

Unfortunately I can't merge this without destroying the commit history, so I'll just have to close this. Sorry again for not responding to this in time. I really appreciate your amazing work!

**Comment by aa-ko** [comment]
@k4yt3x Wow, you actually just casually dropped the C++ rewrite, I am speechless :open_mouth:
 
As far as I can tell, this looks exactly like what I was hoping for. I'll try 6.0.0 ASAP, maybe I can contribute something this time lmao

Thanks for all the hard work, cheers! :tada:

**Comment by k4yt3x** [comment]
@twardoch if you can actually make it work for mac that'll be amazing. I never had a mac in my life so it'll be hard for me to make that work. As for steps to build, here's for Debian/Ubuntu:

https://github.com/k4yt3x/video2x/blob/411cca4e92a275b1f8626a4c47b9a5040399f754/Makefile#L36-L54

Another one is for Arch in [PKGBUILD](https://github.com/k4yt3x/video2x/blob/dev/PKGBUILD).

**Comment by twardoch** [comment]
The Homebrew package installer for macOS does include "ncnn", but I'm not sure if that means that anything will have to be adapted from vulkan to another backend. Right now the macOS situation for AI is very complicated because drastically different backends are used for the new Apple Silicon Macs (where there are more inference acceleration possibilities) vs. the older Intel Macs (which often can do only CPU inference).

**Comment by twardoch** [comment]
Ps. Many local AI packages only exist for the Apple M-Silicon Macs because the older Apple Intel hardware is basically completely unsuitable for local AI inference. 

For example Topaz Video AI runs like 50x faster on my MacBook Air M3 than on a beefy MacBook Pro Intel that's less than 3 years older. 

So it's running time of 3 minutes vs. 2 hours to complete the same task.

**Comment by mirh** [comment]
That sounds like a mac problem, I'm skeptical that even without a npu a properly accelerated coffee lake could be [so](https://www.notebookcheck.net/M3-vs-i7-8565U-vs-i5-8257U_15110_10082_11433.247596.0.html) behind

Anyhow, is RESRGAN supposed to be the only supported driver now?

**Comment by k4yt3x** [comment]
@mirh there's also libplacebo, which renders Anime4K v4 now, but it should be compatible with any MPV compatible GLSL

**Comment by mirh** [comment]
Their paper speaks truth, and all things considered I would also probably recommend this as the "overall" default.
But IIRC from my ancient tests, while RealSR may generally be blurrier (though while still retaining the most detail in the market bar W2xEX's "photo-conservative") I did find it less *foolhardy* too. Like, at least in my 360p video whatever the exaggeration it could produce still felt "natural" (as in "smoothly transitioning with the rest of the picture"), unlike some of the oversharpening blunders of RESRGAN. 

Similarly with an anime DVD, while not "wildly making stuff up" (when the camera pans a scene with a corrugated iron roof and a metal fence it seems like they are dancing with CUGAN) you can still slightly tell in certain places that it is trying *too much* (so for this reason waifu2x seems a solid "safe ground"). 
Presumably temporal stability isn't going to be anywhere near a concern if you are working with higher resolution content.

And last but not least, just a few months ago I figured out that somehow *SRMD* (which I had always thought to be always strictly inferior to the alternatives at least as far as quality was concerned) could give me the best results bar none with a 369x207 crop of a picture from my phone.

**Comment by k4yt3x** [comment]
I've been away for long enough to not know what the best options are anymore. In addition to collecting opinions I'd also like to have the decision of what to add backed by testing results like VMAF. It's a bit beyond my ability to do it all by myself. Ideally we create an environment where people can discuss and vote... perhaps try bringing this up in the telegram group or something?

**Comment by mirh** [comment]
I'm also very much out of the loop, but honestly there hasn't been that much activity in the last years (I assume there's just so much you can do with tiny generic networks?). At most there might be slightly different trained models (that is a [madhouse](https://phhofm.github.io/upscale/favorites.html) tbf)?

As for "objective testing®" I cannot recommend enough [FFMetrics](https://github.com/fifonik/FFMetrics) (and then maybe [this](https://github.com/pixop/video-compare)?).

**Comment by k4yt3x** [comment]
Both look interesting. Perhaps I should set up some kind of a feature poll in the discussions for people to discuss and vote for any new model that should be implemented. My specialty is not actually in AI nor CV, so I would really like if people actually from those fields can bring up and discuss what's worth implementing.

**Comment by mirh** [comment]
Having eyes (and probably lot of time to waste) is probably more important here than knowledge.. like, papers do it too.

One super dope thing that is missing if any, is some easy automatic way to test/compare different solutions (a bit like [this](https://github.com/CrypticSignal/video-quality-metrics) perhaps, but for models rather than compression settings.. even though those would be interesting too now that I think). 
Like, what I used to do was using FFMetrics to find the most different timestamps (not just with the source, but also between each other), then seek for it and compare the different MPC windows.

**Comment by k4yt3x** [comment]
@twardoch I opened a new issue for mac support. If you make any progress could you please post them there? Thanks.
https://github.com/k4yt3x/video2x/issues/1189

**Pull request closed without merging**
