### PR TITLE
Fix container build for 5.0.0-beta7

### PR DESCRIPTION
**Pull request by LukeShortCloud**
This fixes various issues with the container build which is currently broken.

### CODE REVIEW

**Comment by LukeShortCloud** [comment]
Further testing shows that the install with the updated Python 3.9 is partially broken (despite the container build working).

```
$ video2x
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "/usr/local/bin/video2x", line 5, in <module>
    from video2x import main
  File "/usr/local/lib/python3.9/dist-packages/video2x/__init__.py", line 32, in <module>
    from .video2x import Video2X
  File "/usr/local/lib/python3.9/dist-packages/video2x/video2x.py", line 46, in <module>
    from cv2 import cv2
  File "/usr/local/lib/python3.9/dist-packages/cv2/__init__.py", line 8, in <module>
    from .cv2 import *
ImportError: numpy.core.multiarray failed to import
$ python3.9 -m pip install -U numpy
Collecting numpy
  Downloading numpy-1.26.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
     |████████████████████████████████| 18.2 MB 192 kB/s 
Installing collected packages: numpy
Successfully installed numpy-1.26.1
$ video2x
Traceback (most recent call last):
  File "/usr/local/bin/video2x", line 5, in <module>
    from video2x import main
ImportError: cannot import name 'main' from 'video2x' (/usr/local/lib/python3.9/dist-packages/video2x/__init__.py)
```

**Comment by LukeShortCloud** [comment]
The problem is related to the `docker.io/nvidia/vulkan` container using Ubuntu 20.04. The `python3-*` packages are for Python 3.8 (not 3.9 or any other version). I need to rework the installation of dependencies to account for this.

```
$ grep VERSION= /etc/os-release
VERSION="20.04.3 LTS (Focal Fossa)"
```

**Comment by LukeShortCloud** [comment]
I fixed up Python 3.9 support and added optional dependencies so the AI models and libraries are installed. Now I'm running into some codec issues that I'm investigating into.

**Comment by pixlmint** [comment]
Hi @LukeShortCloud have you managed to get it building? I'm also trying to get a custom build of the image working, but I've also run into those issues

**Comment by LukeShortCloud** [comment]
@pixlmint Unfortunately, I am stuck. The container builds again but if you run it, there are various errors. I am unsure if the Python 3.9 or video2x is at fault. Maybe @k4yt3x can give this a look/try and see if they can help fix the lingering issues? I can provide more logs and info this weekend.

**Comment by pixlmint** [comment]
@LukeShortCloud what did you have to change to get it to build? I tried with your fork, and it's failing with this error:

```
 ERROR: Package 'video2x-5.0.0b7' requires a different Python: 3.8.10 not in '>=3.9'
```

**Comment by pixlmint** [comment]
@LukeShortCloud It worked fine for me. Perhaps it's the video you were using? [Here's](https://drive.google.com/file/d/1zAG5_nZzHecSrh0w9l5W_jMil1IDNvEX/view?usp=sharing) a link to the file that I used

**Comment by k4yt3x** [comment]
I pushed an update which fixes the container. It should work now. You can close this PR if it works.

**Comment by LukeShortCloud** [comment]
Thanks @k4yt3x , the latest local build is working for me!

**Pull request closed without merging**
