### PR TITLE
Added Google Colab to readme

### PR DESCRIPTION
**Pull request by Felixkruemel**

### CODE REVIEW

**Comment by k4yt3x** [comment]
I will merge this PR along side other PRs.

**Comment by Felixkruemel** [comment]
@k4yt3x 
If you can please merge :)

**Comment by k4yt3x** [comment]
Sorry school had been really stressful. I'll try to take care of it ASAP.

**Review by k4yt3x — APPROVED** [review]

**Comment by k4yt3x** [comment]
Merged it! I've also updated it a little bit.
Thanks for bring v2x onto a new platform.

**Pull request merged**
