### PR TITLE
Step-by-step instuction and command-line hints for newcomers

### PR DESCRIPTION
**Pull request by Smarthard**
Hello there!
I saw that some people have problems with getting started. So, I decided to help with explanation of installation and added some basics of command prompt usage in README. Hope it helps.

P.S. Ensured that there were no errors in the text, but they could still stay there. Very sorry for that. English isn't my native language.

### CODE REVIEW

**Comment by K4YT3X** [comment]
Hi @Smarthard, thanks for the PR.

I read through your PR, and I do think this repo need some more detailed tutorials like this. I appreciate your effort writing this long step-by-step walkthrough. However, the README file already contains a lot of command examples. I think adding even more instructions into the README file will make the file too "heavy" and confuse the newcomers.

Indeed, people need to learn how to install Python, but that shouldn't be this repositoy's job. We can put links to instructions, or at most, tutorials to installing it, within a separate markdown file. The README file is already too bloated. I don't want it to grow even bigger.

Also, I think making a **video tutorial** will be more intuitive than just pure documentation, so I have been planning on making a video tutorial. However, since my Windows runs on a virtualized environment, it makes things a little too complex to be executed. I'm expecting to get started with it some time within the next week.

**Comment by K4YT3X** [comment]
I do think it's a good idea to include a walkthrough though, just in a separate file.
I'll request some changes to be done to this PR, and put the extra content in a different file like `/doc/step-by-step.md`

**Comment by Smarthard** [comment]
>Also, I think making a video tutorial will be more intuitive than just pure documentation
Yep, I agreed.

>I do think it's a good idea to include a walkthrough though, just in a separate file

That is a good solution too. By the way, we could write a wiki for this repository. Not sure how it works here, but I think it would be more intuitive way than just a separate file placed somewhere in repository.

**Comment by K4YT3X** [comment]
> we could write a wiki for this repository

Yeah that's a better idea. I haven't dealt with wiki much and I'm not familiar with it. I'll see if you can create PRs for it or if I can allow you to modify it.

**Comment by Smarthard** [comment]
It looks like wiki available for changes for any logged-in user. For example, here is [OpenJK wiki](https://github.com/JACoders/OpenJK/wiki/Singleplayer-Overview) page.

However, creating an PRs to wiki pages for wiki pages looks weird and, actually, not officially supported in Github. Take a look [here](https://stackoverflow.com/a/11481887).

**Comment by K4YT3X** [comment]
If it's okay with you, I'll just enable public wiki editing for a few hours or so so you can add your content in there, and I can make changes to the changes that you make if necessary.

**Comment by Smarthard** [comment]
Hello! I'm sorry for taking so long to respond.

>I'll just enable public wiki editing for a few hours

Yeah, it's ok. Just let me know when I can start. Or you can do it youself with necessary modifications as you like.

**Comment by K4YT3X** [comment]
@Smarthard I'll allow modification to wiki right now, and you can get started with it.
I'll review your edits after you're done.

**Comment by K4YT3X** [comment]
Please edit this page: https://github.com/K4YT3X/video2x/wiki/Step-By-Step-Tutorial

**Comment by Smarthard** [comment]
@K4YT3X Well, I copied instructions from my PR.  Please check. I'll correct if you find typos or something else.

**Comment by K4YT3X** [comment]
@Smarthard ok got it. I'm going to close editing down so the wiki won't be tampered with.
I'll be fixing any errors and adding screenshots.

**Comment by K4YT3X** [comment]
I first tried to modify your page, but then I found that it lacks too many details and screenshots, so I rewrote the page with extra details and screenshots. Take a look.

**Comment by Smarthard** [comment]
Wow! Thats much better than mine!

There are just a couple of minor issues:
- Some anchor links doesn't work
- Is it so necessary to use *nix-style PS (like these: `$ python video2x_setup.py`)? I think that this would be confusing for people which are unfamiliar any consoles.

**Comment by K4YT3X** [comment]
> Some anchor links doesn't work

Could you please provide the links that don't work?

> Is it so necessary to use *nix-style PS (like these: $ python video2x_setup.py)?

No it's not. I'll look up the conventions to make sure that I'm following the standard while making it more intuitive.

**Comment by Smarthard** [comment]
Yep, it seems that  now all links work fine.

**Comment by Smarthard** [comment]
By the way I would like to open an issue about running video2x on linux and other *nix family operation systems. I know that this topic is not for this PR. But I may assist you with writing some bootstrapping shell scripts and testing.

**Comment by K4YT3X** [comment]
I initially designed this script for Linux, but it was harder to compile and configure the [original waifu2x](https://github.com/nagadomi/waifu2x) implemented with Torch and Lua for Linux, so I moved on to Windows which has binaries that are easier to use and writing a wrapper around.

Feel free to open a feature request. It's not coming out any time soon, since I'll have to overcome some technical barriers, and a lot of testing is required to make sure that everything works okay. I'll also have to install a different Linux VM with PCI passthrough so I can actually test anything.

**Pull request closed without merging**
